Repository elchininet/ColorTranslator, pull requests merged in 2023-01, with the labels that each got.

#88 Upgrade rollup-plugin-ts to the latest version
  package.json
  yarn.lock
Labels: dependencies

#89 Fix RYB to RGB conversion
  CHANGELOG.md
  dist/web/colortranslator.js
  docs/scripts/bundle.js
  src/color/translators.ts
Labels: bug, conversion

#91 Fix rounding values of hexadecimal colors
  CHANGELOG.md
  rollup.config.js
  src/color/css.ts
  src/color/utils.ts
  src/constants/index.ts
  src/constants/numbers.ts
  src/helpers/index.ts
  src/index.ts
  tests/color-mixing.test.ts
  tests/instance-set-properties.test.ts
  tests/tests.constants.ts
Labels: bug, conversion

#95 Enforce no trailing spaces
  .eslintrc.js
  src/color/css.ts
  src/color/translators.ts
  src/color/utils.ts
Labels: configuration

#96 Improve CSS builder module
  dist/web/colortranslator.js
  package.json
  src/@demo/demo.js
  src/@demo/demo1/index.js
  src/@demo/demo10/index.js
  src/@demo/demo6/index.js
  src/@demo/demo7/index.js
  src/@demo/demo8/index.js
  src/@demo/demo9/index.js
  src/color/css.ts
  src/color/utils.ts
  src/constants/enums.ts
  src/constants/regexps.ts
  src/helpers/index.ts
Labels: refactoring

#97 Refactor blending utilities
  src/constants/numbers.ts
  src/index.ts
Labels: refactoring

#102 Lint test files
  package.json
  tests/blending.test.ts
  tests/color-mixing.test.ts
  tests/harmony.test.ts
  tests/hsl.test.ts
  tests/instance-get-properties.test.ts
  tests/instance-set-properties.test.ts
  tests/shades-tints.test.ts
  tests/static-color-conversion.test.ts
Labels: configuration

#101 minor reformat of helpers
  src/color/utils.ts
  src/helpers/index.ts
Labels: refactoring
